second commit
wjdtnghks123/Rock-Paper-Sicssors pull request #1
Opened 2022-11-21 12:36 UTC by wjdtnghks123

안녕하세요 @smart8612 님
사제동행 강좌를 통해 만나게 되어 반갑습니다. 

사용자 입력을 받아 컴퓨터와 하는 가위바위보 게임을 만들었습니다. 
모든 코드를 파일 하나에 담아두었습니다. 코드를 이해하실 수 있도록 주석을 달았습니다. 
PySide6==6.4.0.1
PyQt6==6.4.0
python==3.10.6

제가 누군가가 보기 위한 코드를 작성한다는 게 처음이라 어떻게 할 지 몰라서 
제가 아는 선에서 노력을 해보았는데 많이 부족하다고 느껴집니다. 
많이 부족하고 엉망이라 고칠 부분이 많이보입니다.
대략적으로 말씀해주시면 제가 열심히 고쳐보겠습니다.

2022-11-22 06:02 UTC, smart8612 commented
안녕하세요! @wjdtnghks123

게임이 오류 없이 잘 작동 되어서 재미 있게 플레이 해볼 수 있었 어요!
수고하셨습니다! 🥳

저 또한 파이썬 초보 사용자 이기 때문에 고급 문법의 사용 등을 보기 보다는 
협업을 위한 코딩 스타일 을 맞추 거나 프로젝트의 유지 보수가 용이 하도록 
개선할 수 있는 방향 으로 초점을 맞추어 리뷰를 진행했습니다.

### 코딩 스타일
협업 과정 에서 코딩 스타일 을 맞추면 코드의 가독성도 개선할 수 있고,
다른 사람 들이 내 코드를 쉽게 이해할 수 있도록 도와줄 수 있다고 생각 합니다.

이번의 경우는 PEP8 스타일 을 기준 으로 리뷰를 진행했습니다.
코드 리뷰를 참조 하실 때, PEP8 가이드 문서를 가볍게 훑어 보시면 더욱 도움이 될 수 있을 것 입니다.
추후, 협업 시에는 기존에 프로젝트 에서 사용 되는 스타일 을 참조 하거나, 
동료와 사용할 스타일 을 협의 하는 과정을 통해 맞춰 나가는 것도 좋은 방법이 될 수 있을 것으로 생각 됩니다.

매번 가이드 를 찾아 가며 코딩 스타일 을 맞추는 것은 쉬운 일이 아닐 수 있다고 생각 합니다.
각종 `lint` 프로그램 을 사용 하면 자동 으로 스타일 룰을 벗어난 코드 조각을 찾고 수정할 수 있도록 도와 줍니다.
제가 사용한 PyCharm IDE 의 경우 PEP8 을 기준 으로 코딩 스타일 을 검사 및 수정 해주는 lint 가 설정되어있는데,
자주 사용하시는 IDE나 코드 편집기의 설정을 확인 해 보시면 좋을 것 같습 니다.

2022-11-22 06:27 UTC, smart8612 requested changes
안녕하세요! @wjdtnghks123

게임이 오류 없이 잘 작동 되어서 재미 있게 플레이 해볼 수 있었어요!
수고하셨습니다! 🥳

저 또한 파이썬 초보 사용자 이기 때문에 고급 문법의 사용 등을 보기 보다는 
협업을 위한 코딩 스타일 을 맞추 거나 프로젝트 의 유지 보수가 용이 하도록 
개선할 수 있는 방향 으로 초점을 맞추어 리뷰를 진행했습니다.

제 의견 또한 틀릴 가능성 이 높으며 정답도 아닙 니다!
wjdtnghks123 님의 좋은 의견이 있다면 코멘트 답장을 통해 언제 든지 의견을 남겨 주세요!~

---

### 코딩 스타일
협업 과정 에서 코딩 스타일 을 맞추면 코드의 가독성도 개선할 수 있고,
다른 사람 들이 내 코드를 쉽게 이해할 수 있도록 도와줄 수 있다고 생각 합니다.

이번의 경우는 PEP8 스타일 을 기준 으로 리뷰를 진행했습니다.
코드 리뷰를 참조 하실 때, PEP8 가이드 문서를 가볍게 훑어 보시면 더욱 도움이 될 수 있을 것 입니다.
추후, 협업 시에는 기존에 프로젝트 에서 사용 되는 스타일 을 참조 하거나, 
동료와 사용할 스타일 을 협의 하는 과정을 통해 맞춰 나가는 것도 좋은 방법이 될 수 있을 것으로 생각 됩니다. 

매번 가이드 를 찾아 가며 코딩 스타일 을 맞추는 것은 쉬운 일이 아닐 수 있다고 생각 합니다.
각종 `lint` 프로그램 을 사용 하면 자동 으로 스타일 룰을 벗어난 코드 조각을 찾고 수정할 수 있도록 도와 줍니다.
제가 사용한 PyCharm IDE 의 경우 PEP8 을 기준 으로 코딩 스타일 을 검사 및 수정 해주는 lint 가 설정 되어 있는데,
자주 사용 하시는 IDE 나 코드 편집기 의 설정을 확인 해 보시면 좋을 것 같습 니다.

### 코드 설계
코드 리뷰 과정 에서 언급하였지만, 현재 프로젝트 구조는 GUI 코드와 게임 로직이 동일한 클래스 내에 함께 구현 되어,
게임 로직의 검증, CLI 와 같은 다른 방식의 UI 로 확장 개발이 어려운 구조 라고 생각 합니다.

이 문제는 wjdtnghks123 님 만의 문제가 아닙 니다.
저를 포함한 다른 프로그래머 들도 GUI 프로그래밍 과정 에서 코드 설계시 많은 고민을 하게 되는 부분이 될 수 있다고 생각 합니다.
전통적인 해결 방법은 `#Model-View-Controller` (MVC 패턴) 라고 불리는 코드 설계 방법이 존재 합니다.
이 방법을 찾아 보시면 문제 해결에 도움이 될 수 있을 것으로 생각 합니다.

개발 방법론 을 통해 좋은 코드 설계 구조로 수렴해 나가는 방법도 있습 니다.
제가 소개해 드리는 방법은 테스트 주도 개발 방법론 (TDD) 이라고 부릅 니다.
이 키워드 를 구글 에서 찾아 보시면 단위 테스트 를 활용한 TDD 방법이 많이 소개 되어 있으니
시도해 보시면 도움될 수 있을 거라 생각합니다!

### 의존성 관리
프로젝트 를 구동 하기 위해 어떤 모듈이 필요 한지, 어떻게 설치 하는 지에 관한 문서를 찾을 수 없었 습니다.
README 등의 문서를 통해 필요한 의존성이나 실행 환경 등을 설명 해 주시면 
처음 사용자 가 손쉽게 프로젝트 를 구동 하는데 큰 도움이 될 수 있을 것이라 생각 합니다.
(인간의 기억력이 좋지 않을 수 있으니 미래의 자신을 위한 문서가 될 수 있습 니다)
파이썬 패키지 관리자를 통해 손쉽게 의존성을 설치할 수 있도록 환경을 구축해 주시면
더욱 편리해질 수 있을 것 같아요! 이와 관련하여 설명된 문서를 첨부해 드리니 개선시 활용해 보세요!
[pip.pypa.io - requirements files](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
[PEP8 - imports](https://peps.python.org/pep-0008/#imports)

style guide 에서 import 의 순서에 대한 설명을 찾았습니다.
순서는 다음과 같습니다.

1. Standard library imports (sys, random 모듈이 해당될 수 있어요)
2. Related third party imports (PySide, PyQt 모듈이 해당될 수 있어요!)
3. Local application/library specific imports

파이썬 모듈의 import 코드의 작성 순서를 위와 같이 개선 해보는 것은 어떨 까요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
[PEP328 - Rationale for Parentheses](https://peps.python.org/pep-0328/#rationale-for-parentheses)

2 ~ 3번 행의 코드 처럼 어느 모듈에 대한 다중 import 가 이뤄질 때, 참조할 수 있는 가이드 라인을 다음과 같이 찾았습니다.
* 백 슬래쉬(**/**) 를 활용한 방법
* 다중 import 문을 작성 하는 방법
* 현재 사용 하신 방법과 동일한 괄호를 이용한 그룹핑 방법

[PEP8 - Indentation](https://peps.python.org/pep-0008/#indentation)

3번 행에서 사용하신 코드 들여쓰기 방법 케이스와 매칭되는 가이드를 찾지는 못했으나, 이와 유사한 코드 들여쓰기 가이드를 찾았습니다.
다른 방법의 코드 들여 쓰기도 한번 확인 해보면 좋을 것 같아요!


현재 사용 하신 방법을 선택(혹은 선호) 하는 이유는 무엇 인가요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +class Form(QDialog):
[PEP-8 Blank Lines](https://peps.python.org/pep-0008/#blank-lines)

코드를 작성할 때 빈 줄을 넣는 방식 등을 사용 하여 코드 레이 아웃을 잡는 가이드 라인을 찾았 어요!

> Surround top-level function and class definitions with two blank lines.

클래스의 정의 부를 모듈 import 부분과 메인 함수 영역과 구분 지어 보면 어떨까요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
함수 내부 에서 사용 하신 개행 방식이 궁금 합니다!

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +        self.user_edit = QLineEdit("당신의 선택, form : 마지막 띄어쓰기 한 칸 , ex : '가위 ' ")
사용자가 기본 메시지를 지우지 않고도 "가위 ", "바위 ", "보 " 를 입력할 수 있다면 사용자 경험이 더욱 개선될 수 있을 것 같아요!
`#Placeholder`

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
가위, 바위, 보 게임의 동작 로직을 담은 코드로 보입니다.

현재 PyQt 를 통한 GUI 로 구동 하고 있는데,
만약 이 프로젝트를 터미널에서 구동하는 CLI 프로그램 으로 변환 하고 싶을 때,
해당 게임 로직을 재사용 할 수 있다면 작업 시간을 절약할 수 있을 겁니다.

다만, 현재는 GUI 구동 코드와 게임 로직이 Form 이라는 클래스로 함께 묶여 있어
게임 로직을 재사용하기 어려울 수 있는 구조라고 생각합니다.

게임 로직을 분리 하여 개선해볼 수 있을까요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +    def who_winloss(self) :
[PEP8 - Prescriptive: Naming Conventions](https://peps.python.org/pep-0008/#prescriptive-naming-conventions)

겸사 겸사 파이썬에서 사용되는 네이밍 컨벤션을 한번 찾아봅시다! \
컴퓨터 프로그램에서 변수, 함수, 클래스 등의 네이밍은 어떤 의미로 사용될까요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +            if str(self.user_edit.text()) == "가위 " :
현재와 같은 구조 에서는 만약 가위 바위 보를 Rock, Paper, Scissors 로 바꿔야 할 때, 코드에 있는 가위, 바위, 보 를 하나씩 하나씩 찾아서 수정 해야 할 수 있는 문제가 발생될 수 있다고 생각 합니다.

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
[PEP8 - Whitespace in Expressions and Statements](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)

위 코드 중 함수의 정의부 ":" , 배열의 element 간 ",", QColor(255,255,255) 내부 에서 사용한 공백의 사용 기준을 설명해주세요!

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +            if str(self.user_edit.text()) == "가위 " :
[docs.python.org - unittest](https://docs.python.org/ko/3/library/unittest.html)

게임 로직이 잘 동작하는지 코드를 검증 해볼 수 있는 방법이 있을 까요?

2022-11-22 06:27 UTC, smart8612 commented on pyqt.py
> +
파이썬 패키지 의존성을 손쉽게 관리할 수 있는 방법은 무엇이 있을 까요?

2022-12-01 10:19 UTC, wjdtnghks123 commented on pyqt.py
> +
링크 걸어주신 문서 읽은 후 수정하였습니다!! 😁 

궁금한 점이 있습니다. 여러 개를 import 할 때 

from A import B, C, D, E ->  from A import B, C 
                                               from A import D, E 

후자가 옳은 방식으로 이해했는데 가독성 때문인가요??

2022-12-01 10:25 UTC, wjdtnghks123 commented on pyqt.py
> +
링크 걸어주신 문서 읽은 후 수정하였습니다!! 😁

import 를 다중 import 문을 작성하는 방법으로 개선하였고, 들여쓰기

2022-12-01 10:39 UTC, wjdtnghks123 commented on pyqt.py
> +class Form(QDialog):
링크 걸어주신 문서 읽은 후 수정하였습니다!! 😁

클래스를 정의할 때 상위 함수(여기서는 import 부분) 사이에 2줄 
클래스 내 함수를 정의할 때 1줄을 비워야 한다고 저는 이해했습니다.
혹시 틀렸다면 comment 부탁드립니다!!

2022-12-01 10:46 UTC, wjdtnghks123 commented on pyqt.py
> +
class 문을 작성하고 줄 바꾼 후 tab 을 눌러 def 문을 작성하였습니다.
class 문과 def 문 사이에 blank line을 추가했으면 더 좋았을 것 같습니다.😅

2022-12-01 10:54 UTC, wjdtnghks123 commented on pyqt.py
> +        self.user_edit = QLineEdit("당신의 선택, form : 마지막 띄어쓰기 한 칸 , ex : '가위 ' ")
Placeholder 에 대해 알아본 후 수정하였습니다!! 😄 
저도 다른 프로그램을 사용할 때 이러한 경험을 하였는데 막상 만들 때는 생각하지 못 했습니다.
기존 문자를 지우고 작성해야하는 불편함을 없앨 수 있게 되었습니다.
좋은 정보 감사합니다! 👍

2022-12-01 11:06 UTC, wjdtnghks123 commented on pyqt.py
> +    def who_winloss(self) :
링크 걸어주신 문서 읽은 후 수정하였습니다!! 😁
원래 생각은 `def who_winlose()`로 할 생각이었습니다. 
최초 작성할 때 loss로 작성 하였고 이후 자동완성 기능을 사용하여 발견하지 못하였습니다. 😥 
함수, 변수 이름은 짧고, 단어를 _(밑줄)로 구분해야 한다는 사실을 발견했습니다.

2022-12-01 11:15 UTC, wjdtnghks123 commented on pyqt.py
> +            if str(self.user_edit.text()) == "가위 " :
만약 만든 프로그램이 계속 업데이트를 진행할 예정이라고 가정한다면 말씀 하신 것처럼 문제가 발생할 것입니다. 
코드 작성 당시에는 생각하지 못하였는데, 정택님의 피드백 덕분에 알게 되었습니다🌟 

가위, 바위, 보에 해당하는 dictionary 를 만들어 value 값으로 우선순위를 준다면 더 좋을 것 같습니다. 
1. 가위, 바위, 보의 이름을 변경할 경우( ex. 영어, 중국어, 일본어 등) - dictionary 에 속한 key 를 변경한다.
2. 가위, 바위, 보의 우선순위를 변경하는 경우 - dictionary 에 속한 key의 value 를 변경한다.

2022-12-01 11:37 UTC, wjdtnghks123 commented on pyqt.py
> +
링크 걸어주신 문서 읽은 후 수정하였습니다!! 😁
함수 정의부와 QColor내부 공백은 문서를 읽고 수정 하였고, 이외 같은 잘못을 한 부분도 수정하였습니다.👏
`result_text = ["  win " , " Lose" , " Draw"]` 이 경우는 글자 크기와 출력창의 크기를 고려하여 
글자마다 띄어쓰기를 다르게 하였습니다.

2022-12-04 03:19 UTC, smart8612 commented
수고하셨습니다. 단 시간에 많은 부분을 개선해주신 것이 보였습니다. 🤩🥳🤩🥳
특히, 공식 문서를 자세히 읽고 좋은 내용을 추려 코멘트 남겨 주신 부분도 큰 도움이 되었습니다.
이번 코드 리뷰 과정에 참여하며 저도 파이썬 코딩 스타일에 대해 배워갈 수 있었던 좋은 계기가 되었어요!
언젠가 또 함께 코드 리뷰를 함께하게 되는 시간이 오면 좋겠네요 ㅎㅎ 다음에 또봐요~🤗

2023-05-18 01:58 UTC, merged